### ISSUE TITLE
How to get images?

### ISSUE THREAD

**Issue by GuiRitter** [jaraco/jaraco.clipboard#1]
Hi there.

How do I use `copy_image()` to get images from the clipboard?

I found no documentation anywhere.

Thanks in advance.

**Comment by jaraco** [comment]
> How do I use copy_image() to get images from the clipboard?

You use `paste_image` to get images from the clipboard.

The docs are currently relegated to [the readme](https://github.com/jaraco/jaraco.clipboard/blob/master/README.rst) and the code. I welcome improvements to the docs.

Presuming you're working on Windows, the only platform currently supporting images, I notice that even there, the 'copy' function is not present, so I'd expect a NotImplementedError to be raised if you were to invoke `jaraco.clipboard.copy_image`... but I would expect `jaraco.clipboard.paste_image()` to return something, as it's [based on this](https://github.com/jaraco/jaraco.windows/blob/6e4a55acb944f090dfe3618fa39c093d48e14c04/jaraco/windows/clipboard.py#L164).

See [here](https://github.com/jaraco/lpaste/blob/bfb1165b374a758cbd303a3f841190cf0809ae7b/lpaste/clipboard.py#L11) for an example that uses paste_image to retrieve an image to jpeg using pillow.

**Comment by GuiRitter** [comment]
Thank you! I finally managed to get this part working. Although the readme has basically no information about images, that example did the trick.
