### ISSUE TITLE
Cannot copy HTML on Darwin (macOS)

### ISSUE THREAD

**Issue by optilude** [jaraco/jaraco.clipboard#4]
Using `copy_html()` on macOS results in plain text being copied. The reason is that the delegation to the underlying `richxerox` API is not correct.

```python
copy_html = functools.partial(richxerox.copy, format='html')
```

however the call signature of `richxerox.copy()` is:

```python
def copy(text=None, clear_first=True, **kwargs):
```

You are meant to do `copy(html=some_html)`. There is no `format=` kwarg.

**Comment by jaraco** [comment]
I see. Yes, I think I assumed the interface was symmetric with the `paste` interface, where `format="html"` is the signal.

**Comment by jaraco** [comment]
Thanks for the report. 2.0.1 is [releasing now](https://travis-ci.org/jaraco/jaraco.clipboard/builds/561523525).
